# docker-compose.prod.yml (Example)
version: "3.8"
services:
  api:
    build:
      context: ./backend
      target: production
    image: kleem/api:latest
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - qdrant
      - minio
      - n8n
    restart: always

  frontend:
    build:
      context: ./frontend
      target: production
    image: kleem/frontend:latest
    environment:
      - VITE_API_BASE=${API_PUBLIC_URL}
    ports:
      - "5173:5173"
    restart: always

  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
    ports:
      - "5678:5678"
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=kleem
      - RABBITMQ_DEFAULT_PASS=please_change
      - RABBITMQ_DEFAULT_VHOST=/kleem
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=kleem
      - MINIO_ROOT_PASSWORD=please_change
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  mongo_data:
  qdrant_data:
  minio_data:
